---
title: "Data Visualization"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)
library(ggwordcloud)
visualSet<-read.csv("C:\\Users\\uvsre\\Desktop\\Data Science 1601\\Final Project\\cleanVGSet.csv")
```

# Part A
```{r message=FALSE, warning=FALSE}
ggplot(visualSet, aes(x=ESRB_Rating))+
  geom_bar(fill=brewer.pal(9,"Set1"))+
  theme(axis.text.x = element_text(angle = 90))+
  labs(x="ESRB Rating", y="Number of Games", title="Distribution of Ratings")

tempVisual1<-visualSet%>%
  group_by(ESRB_Rating,Genre)%>%
  summarise(count=n())

ggplot(tempVisual1, aes(label=Genre,size=count,color=ESRB_Rating))+
  geom_text_wordcloud_area(rm_outside = TRUE)+
  scale_size_area(max_size = 25)

tempVisual2<-visualSet%>%
  group_by(ESRB_Rating,Platform)%>%
  summarise(count=n())

ggplot(tempVisual2, aes(label=Platform,size=count,color=ESRB_Rating))+
  geom_text_wordcloud_area(rm_outside = TRUE)+
  scale_size_area(max_size = 30)

ggplot(data=visualSet, mapping = aes(x=Year))+geom_bar()

ggplot(visualSet,aes(x=Total_Shipped))+geom_histogram(bins = 236,
                                                  fill="yellow", color="black")

ggplot(visualSet,aes(x=Global_Sales))+geom_histogram(bins = 236,
                                                  fill="blue", color="black")

ggplot(visualSet,aes(y=Critic_Score))+geom_boxplot(fill="purple",
                                                outlier.color = "yellow")

ggplot(visualSet,aes(y=User_Score))+geom_boxplot(fill="green",
                                                outlier.color = "red")
```

# Part B
```{r message=FALSE, warning=FALSE}
ggplot(visualSet, aes(x=ESRB_Rating, y=Critic_Score))+
  geom_boxplot(fill="pink")

ggplot(visualSet, aes(x=ESRB_Rating, y=User_Score))+
  geom_boxplot(fill="yellow")

ggplot(visualSet, aes(x=Critic_Score, y=Global_Sales))+geom_point()

ggplot(visualSet, aes(x=User_Score, y=Global_Sales))+geom_point()
```

# Part C
```{r message=FALSE, warning=FALSE}
ggplot(visualSet, aes(x=Critic_Score, y=Global_Sales, color=ESRB_Rating))+
  geom_point(alpha=0.5)+scale_size(range = c(0.1,12))

ggplot(visualSet,aes(x=Year, fill=Genre))+geom_bar(position = "fill")+
  facet_wrap(~ESRB_Rating)
```

